language: julia
os:
  - linux
julia:
  - 0.6
  - nightly
env:
  - TEST_TYPE=basic
  # - TEST_TYPE=bench
  - TEST_TYPE=userimage
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
    - env: TEST_TYPE=bench
  include:
    - if: branch = master
      julia: 0.6
      os: osx
      env: TEST_TYPE=basic
  exclude:
    - julia: nightly
      env: TEST_TYPE=userimage

notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Memento")'
  - ./.travis/test.sh
after_success:
  - julia -e 'cd(Pkg.dir("Memento")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'cd(Pkg.dir("Memento")); Pkg.clone("https://github.com/invenia/Documenter.jl"); Pkg.checkout("Documenter", "rf/deploy-fix"); include(joinpath("docs", "make.jl"))'
