name = "Memento"
uuid = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
license = "MIT"
authors = ["Invenia Technical Computing"]
version = "1.4.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
JSON = "0.16.1, 0.17, 0.18, 0.19, 0.20, 0.21"
Requires = "1"
Syslogs = "0.0.1, 0.1, 0.2, 0.3"
TimeZones = "0.7, 0.8, 0.9, 0.10, 0.11, 1"
julia = "1"

[extras]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Syslogs = "cea106d9-e007-5e6c-ad93-58fe2094e9c4"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[targets]
test = ["JSON", "Suppressor", "Syslogs", "TimeZones"]
